# Generated by Django 5.0.3 on 2024-03-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_vestibular', models.CharField(max_length=30)),
                ('nm_vestibular', models.CharField(max_length=20)),
                ('ano_vestibular', models.IntegerField()),
                ('url_vestibular', models.TextField()),
            ],
        ),
    ]
