# Generated by Django 5.0.3 on 2024-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tests_url_gabarito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='cdn_vestibular',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
