# Generated by Django 5.0.3 on 2024-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tests_cdn_vestibular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='cdn_vestibular',
        ),
        migrations.AddField(
            model_name='tests',
            name='num_vestibular',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
